from .mlp  import MLP
from .gat  import GAT
from .gcn  import GCN
from .h2gcn import H2GCN
from .rgcn import RGCN
from .shgn import myGAT
from .han  import HAN
from .hgt  import HGT
from .linkx import LINKX